on: 
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
#    - name: Hello world action step
#      id: hello
#      uses: ninabcdefghi/automata2@master
#      with:
#        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      uses: actions/checkout@master
    - name: Install Python dependencies
      run: pip3 install -r requirements.txt
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' 
    - name: Get new Data
      run: python3 genderstat.py
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "graph.ipynb"
        params: "PATHTOPARAMS.json"
        isReport: False
        poll: True
    - name: Create local changes
      run: echo acbcbc >> hhhaah
    - name: Commit files
      run: |
        git config --local user.email "tomsurayo@gmail.com"
        git config --local user.name "ninabcdefghi"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
