on: 
  push:
  schedule:
    - cron: '0 8 * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
#    - name: Hello world action step
#      id: hello
#      uses: ninabcdefghi/automata2@master
#      with:
#        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      uses: actions/checkout@master
    - name: Install Python dependencies
      run: pip3 install -r requirements.txt
    - name: Get new Data
      run: python3 genderstat.py
    - name: Create local changes
      run: echo acbcbc >> hhhaah
    - name: Commit files
      run: |
        git config --local user.email "tomsurayo@gmail.com"
        git config --local user.name "ninabcdefghi"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
